---
# Add all dependent roles, that should be executed before
# the content of this role. If this is an appliance
# there should always be atleast these 3 includes

# Change needed roles here
- name: download dependencies from galaxy
  shell: ansible-galaxy install uniqconsulting.os_basic uniqconsulting.open_vm_tools uniqconsulting.firewall uniqconsulting.nginx uniqconsulting.php uniqconsulting.mariadb

# Include all roles like this:

- name: uniqconsulting.os_basic
  include_role:
    name: uniqconsulting.os_basic
  vars:
    osbasic_selinux: true
    osbasic_selinux_policy: disabled
    osbasic_os_update: true
    osbasic_package_cleanup: true
    osbasic_package_upgrade: all
    osbasic_epel: true
  when: not webserver_update_only

- name: uniqconsulting.open_vm_tools
  include_role:
    name: uniqconsulting.open_vm_tools
  when: install_openvmtools and not webserver_update_only
      
- name: uniqconsulting.firewall
  include_role:
    name: uniqconsulting.firewall
  vars:
    firewall_open_ports: "{{ role_ports + additional_open_ports }}"
  when: not webserver_update_only


- name: create nginx user (needed for php)
  user:
    name: nginx
    system: yes
    shell: /usr/sbin/nologin
    create_home: no
  when: not webserver_update_only
  
- name: uniqconsulting.php
  include_role:
    name: uniqconsulting.php
  when: not webserver_update_only
  
- name: uniqconsulting.nginx
  include_role:
    name: uniqconsulting.nginx
  vars: 
    nginx_geoip: yes
    nginx_vhosts: []
    nginx_default_document_root: "{{ webserver_document_root }}"
  when: not webserver_update_only
      

...